### ISSUE TITLE
Returning data to fetch

### ISSUE THREAD

**Issue by hajsf** [SergioBenitez/Rocket#1080]
Trying to replicate the [form_kitchen_sink](https://github.com/SergioBenitez/Rocket/tree/master/examples/form_kitchen_sink) using JavaScript fetch, as:

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

use std::io;

use rocket::request::{Form, FormError, FormDataError};
use rocket::response::NamedFile;
use rocket::http::RawStr;

#[derive(Debug, FromFormValue)]
enum FormOption {
    A, B, C
}

#[derive(Debug, FromForm)]
struct FormInput<'r> {
    checkbox: bool,
    number: usize,
    #[form(field = "type")]
    radio: FormOption,
    password: &'r RawStr,
    #[form(field = "textarea")]
    text_area: String,
    select: FormOption,
}

#[post("/", data = "<sink>")]
fn sink(sink: Result<Form<FormInput>, FormError>) -> String {
    match sink {
        Ok(form) => format!("{:?}", &*form),
        Err(FormDataError::Io(_)) => format!("Form input was invalid UTF-8."),
        Err(FormDataError::Malformed(f)) | Err(FormDataError::Parse(_, f)) => {
            format!("Invalid form input: {}", f)
        }
    }
}

#[get("/")]
fn index() -> io::Result<NamedFile> {
    NamedFile::open("static/index.html")
}

fn rocket() -> rocket::Rocket {
    rocket::ignite().mount("/", routes![index, sink])
}

fn main() {
    rocket().launch();
}
```
And static file as:
```html
<h1>Rocket Form Kitchen Sink</h1>

<form id="myForm" action="/" method="post" accept-charset="utf-8">
    <label>Checkbox:
        <input type="checkbox" name="checkbox" value="on">
    </label><br /><br />

    <label>Number:
        <input name="number" type="number" value="123" />
    </label><br /><br />

    <label>Password:
        <input name="password" type="password" />
    </label>
    <br /><br />

    <label for="type">Type:
        <label for="a">A
            <input type="radio" name="type" id="a" value="a" />
        </label>
        <label for="b">B
            <input type="radio" name="type" id="b" value="b" checked />
        </label>
        <label for="c">C
            <input type="radio" name="type" id="c" value="c" />
        </label>
    </label>
    <br /><br />

    <label>Textarea:
        <textarea name="textarea" rows="10" cols="50">Write something here.</textarea>
    </label>
    <br /><br />

    <label>Select:
        <select name="select">
            <option value="a">Value A</option>
            <option value="b" selected>Value B</option>
            <option value="c">Value C</option>
        </select>
    </label>
    <br /><br />

    <label>Submit:
        <input type="submit" value="Login">
    </label>
    <br /><br />


</form>

<button onclick="submit(document.forms['myForm'])">Submit</button>
<button onclick="submit(document.querySelector('#myForm'))">Submit</button>

<script>
  function submit(form){
      url = '/';

        const formData = new FormData(form);
        fetch(url, {
          method: 'post',
          body: formData, // post body

          headers: {
           'Content-Type': 'application/x-www-form-urlencoded'
          }
      }).then(function(response){
        console.log("returned response: "+ response);
        console.log("returned response: "+ response.text);
        console.log(JSON.stringify(response))
            console.log(response.headers.get('Content-Type'));
            console.log(response.headers.get('Date'));

            console.log(response.status);
            console.log(response.statusText);
            console.log(response.type);
            console.log(response.url);

      }).then(function(oData){
        console.log(JSON.stringify(oData)); // console.log("returned text: "+ oData);
      }).catch(function(error){
        console.log("returned error: "+ error);
      })
  }
</script>
```
But could not read the returned data from Rocket to the fetch, below the screen shoot of what I got:

![image](https://user-images.githubusercontent.com/46838626/62615479-feb16080-b915-11e9-966e-b80d4db0ac2a.png)

**Comment by SergioBenitez** [comment]
I'm going to assume based on #1081 that this was resolved.

**Comment by hajsf** [comment]
Actually half yes, half no, it worked with me by returning `JsonValue` instead of `String`, my code now is:

```rust
#[post("/", data = "<sink>")]
fn sink(sink: Result<Form<FormInput>, FormError>) ->   JsonValue { 
    println!("{:#?}", &sink);
    match sink {
        Ok(form) => {
            json!({
            "status": "success",
            "reason": format!("{:?}", &*form)
          })
        },
        Err(FormDataError::Io(_)) => {
            json!({
            "status": "error",
            "reason": format!("Form input was invalid UTF-8.")
          })
        },
        Err(FormDataError::Malformed(f)) | Err(FormDataError::Parse(_, f)) => {
            json!({
            "status": "error",
            "reason": format!("Invalid form input: {}", f)
          })
        }
    }
}
```

And my `JavaScript` as:
```JavaScript
  function submit(form){
      url = '/';

        const formData = new FormData(form);

            (async () => {
      const rawResponse = await fetch('/', {
        method: 'POST',
        headers: {
          'Accept': 'application/x-www-form-urlencoded',
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        body: formData
      });
      const content = await rawResponse.json();

      console.log(content);
      })();
  }
```

But:
1. The issue of returning a `String` is not resolved
2. The returned result is always `Err(FormDataError::Malformed(f))`

In server I got"
```bash
    => Error: The request's form string was malformed.
Err(
    Malformed(
        "------WebKitFormBoundaryvgpNxAaUb2yZAH7o\r\nContent-Disposition: form-data; name=\"checkbox\"\r\n\r\non\r\n------WebKitFormBoundaryvgpNxAaUb2yZAH7o\r\nContent-Disposition: form-data; name=\"n
umber\"\r\n\r\n123\r\n------WebKitFormBoundaryvgpNxAaUb2yZAH7o\r\nContent-Disposition: form-data; name=\"password\"\r\n\r\n4242\r\n------WebKitFormBoundaryvgpNxAaUb2yZAH7o\r\nContent-Disposition: form
-data; name=\"type\"\r\n\r\nc\r\n------WebKitFormBoundaryvgpNxAaUb2yZAH7o\r\nContent-Disposition: form-data; name=\"textarea\"\r\n\r\nWrite something here. 254\r\n------WebKitFormBoundaryvgpNxAaUb2yZA
H7o\r\nContent-Disposition: form-data; name=\"select\"\r\n\r\nc\r\n------WebKitFormBoundaryvgpNxAaUb2yZAH7o--\r\n",
    ),
)
```

![image](https://user-images.githubusercontent.com/46838626/62678700-ddef1680-b9ba-11e9-8c70-a8d0397affaf.png)

And in the browser side I got the same:
