### ISSUE TITLE
Error: Response was `Err`: DatabaseError

### ISSUE THREAD

**Issue by uncode** [SergioBenitez/Rocket#400]
this is my request guard for database
```
static DATABASE_URL: &'static str = env!("DATABASE_URL");

/// Initializes a database pool.
fn init_pool() -> Pool {
    let config = r2d2::Config::default();
    let manager = ConnectionManager::<MysqlConnection>::new(DATABASE_URL);
    r2d2::Pool::new(config, manager).expect("db pool")
}


use std::ops::Deref;
use rocket::http::Status;
use rocket::request::{self, FromRequest};
use rocket::{Request, State, Outcome};


pub struct DbConn(pub r2d2::PooledConnection<ConnectionManager<MysqlConnection>>);

impl<'a, 'r> FromRequest<'a, 'r> for DbConn {
    type Error = ();

    fn from_request(request: &'a Request<'r>) -> request::Outcome<DbConn, ()> {
        let pool = request.guard::<State<Pool>>()?;
        match pool.get() {
            Ok(conn) => Outcome::Success(DbConn(conn)),
            Err(_) => Outcome::Failure((Status::ServiceUnavailable, ()))
        }
    }
}

// For the convenience of using an &DbConn as an &SqliteConnection.
impl Deref for DbConn {
    type Target = MysqlConnection;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
```

logic code

```
#[get("/list")]
fn list(db: DbConn) -> QueryResult<Json<Vec<JobModel>>> {
    use schema::job;
    use schema::job::dsl::*;
    //    let results = job.load::<JobModel>(&*db).expect("Error loading blogs");
    //    ok!(results)
    job.load::<JobModel>(&*db)
        .map(|tasks| Json(tasks))
}
```

when I request this URL, I got `Error: Response was `Err`: DatabaseError(__Unknown, "Commands out of sync; you can\'t run this command now"). `
 `````
    Finished dev [unoptimized + debuginfo] target(s) in 4.65 secs
     Running `target/debug/rocket-blog`
🔧  Configured for development.
    => address: localhost
    => port: 8000
    => log: normal
    => workers: 16
    => secret key: generated
    => limits: forms = 32KiB
    => tls: disabled
🛰  Mounting '/':
    => GET /list
🚀  Rocket has launched from http://localhost:8000
GET /list text/html:
    => Matched: GET /list
    => Error: Response was `Err`: DatabaseError(__Unknown, "Commands out of sync; you can\'t run this command now").
    => Outcome: Failure
    => Warning: Responding with 500 Internal Server Error catcher.
    => Response succeeded.

```

**Comment by Eijebong** [comment]
Are you using diesel 0.16 ? If not can you try updating ? We fixed a bug that was causing that error when you ran a query with a select statement with .execute(), maybe you're running into it

**Comment by SergioBenitez** [comment]
This doesn't look like it's caused by Rocket. I would suggest reporting it to the Diesel issue tracker if  the issue still occurs on Diesel's latest release.

**Comment by SergioBenitez** [comment]
This doesn't look like it's caused by Rocket. I would suggest reporting it to the Diesel issue tracker if  the issue still occurs on Diesel's latest release.
